### ISSUE TITLE
compile error under indigo

### ISSUE THREAD

**Issue by juwangvsu** [svenschneider/youbot-manipulation#11]
## I am trying to build from source in indigo, this is the error I get, any suggestions?

Building CXX object youbot-manipulation/youbot_arm_kinematics_moveit/CMakeFiles/youbot_arm_kinematics_moveit.dir/ros/src/youbot_arm_kinematics_moveit.cpp.o
/home/student/moveit/src/youbot-manipulation/youbot_arm_kinematics_moveit/ros/src/kinematics_logger.cpp: In member function ‘virtual void KinematicsLogger::write(const string&, const char_, int)’:
/home/student/moveit/src/youbot-manipulation/youbot_arm_kinematics_moveit/ros/src/kinematics_logger.cpp:16:9: error: ‘enabled’ was not decluared in this scope
     if (enabled) {
         ^
/home/student/moveit/src/youbot-manipulation/youbot_arm_kinematics_moveit/ros/src/kinematics_logger.cpp:17:32: error: ‘loc’ was not declared in this scope
         ros::console::print(0, loc.logger_, ros::console::levels::Debug,
                                ^
make[2]: *_\* [youbot-manipulation/youbot_arm_kinematics_moveit/CMakeFiles/youbot_arm_kinematics_moveit.dir/ros/src/kinematics_logger.cpp.o] Error 1

**Comment by svenschneider** [comment]
Hi,

it looks like you are trying to compile the hydro branch under ROS Indigo. That does not work indeed and results in the error that you show. The solution should be rather straight forward, try the indigo branch [1].

Cheers
Sven

[1] https://github.com/svenschneider/youbot-manipulation/tree/indigo

**Comment by juwangvsu** [comment]
Hi,

thanks it works.

Ju Wang, Associate Prof
Math & Computer Science
Virginia State University
Tel (804) 524-3096
Fax (804) 524-5746

**Comment by frederikhegger** [comment]
@svenschneider: I think this one can be closed.
