### ISSUE TITLE
Kinematics Solver

### ISSUE THREAD

**Issue by isaeldoori** [svenschneider/youbot-manipulation#18]
Dear svenschneider,

I´ve been busy working on the youbot for quite a while now and I haven´t gotten the IK to work yet.

I´m running on ubuntu 14.04 and ros indigo.

The error I get when I start the roslaunch youbot_moveit demo.launch is: [ERROR] [1461593350.787814510]: Kinematics solver N10kinematics14KinematicsBaseE does not support joint group arm_1. Error:

I have no idea why the kinematics solver does not work on my youbot, as I cannot find anyone (yet) who had the same problem.

I hope you can help.

Kind regards,

Isa

**Comment by svenschneider** [comment]
Dear Isa,

could you please provide more information of which steps you have performed, including installed software, cloned repositories and build steps? A complete log of the terminal(s) with the executed commands and the resulting output would also be really helpful.

Best regards
Sven

**Comment by svenschneider** [comment]
Closing due to missing feedback.
