### ISSUE TITLE
Question: Is there some documentation about your origin frame etc.

### ISSUE THREAD

**Issue by k1l1** [svenschneider/youbot-manipulation#24]
Hey Sven,

I try to use your code (inverse kinematics) to make my youbot work with position control. Is there some information about what base frame you use. I tried to come up with a description of forward kinematics, but each DH Table I can find on the internet fails. Do you know what reference frame the angles published by the youbot ROS driver have?

Thanks for your help!

**Comment by arafatsh** [comment]
hey K1|1
I also have a youbot,is yours running on kinetic or indigo?
