### ISSUE TITLE
Planner is not able to find any solution on the real robot

### ISSUE THREAD

**Issue by rastaxe** [svenschneider/youbot-manipulation#4]
Hi, I am trying to use your package with a real youbot (Hydro+MoveIt!). I tried to use Commander and rviz to send some goals to the planning, but I always get: 

[ INFO] [1409147480.844621192]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[ INFO] [1409147480.845457053]: Starting state is just outside bounds (joint 'arm_joint_1'). Assuming within bounds.
[ INFO] [1409147480.845675307]: Starting state is just outside bounds (joint 'arm_joint_2'). Assuming within bounds.
[ INFO] [1409147480.845857942]: Starting state is just outside bounds (joint 'arm_joint_3'). Assuming within bounds.
[ INFO] [1409147480.917308438]: No planner specified. Using default.
[ INFO] [1409147480.918721677]: LBKPIECE1: Attempting to use default projection.
[ INFO] [1409147480.948382716]: LBKPIECE1: Starting with 1 states
[ INFO] [1409147486.265920437]: LBKPIECE1: Created 80 (42 start + 38 goal) states in 71 cells (42 start (42 on boundary) + 29 goal (29 on boundary))
[ INFO] [1409147486.266674444]: No solution found after 5.346708 seconds
[ INFO] [1409147486.269393646]: Unable to solve the planning problem

When I start rviz, at the beginning the arm has an init position (see fig.1) and after loading it is in the correct position (fig.2), but the first position is always displayed, is it ok? 
Can you help me? Do you know how to solve my problem?
Thanks!
![1](https://cloud.githubusercontent.com/assets/3437604/4061608/869bc812-2df9-11e4-8510-bd7c03d01aeb.png)
![2](https://cloud.githubusercontent.com/assets/3437604/4061609/86a167ae-2df9-11e4-998b-81a691465f44.png)

**Comment by svenschneider** [comment]
Regarding the "two" robots which you see in RViz: One is the representation of the real robot, i.e. it is updated when you move the real robot. The other one is the internal state of MoveIt! Thus, it's fine that two robots are displayed.

For the failing motion planning, I would guess that it is due to the arm of the real robot being within the soft joint limits. You could try to move all joints of the arm a little bit manually (or move the arm to another configuration) and then try again.

**Comment by rastaxe** [comment]
I tried to move the arm but it does not help. But, why the internal state of MoveIt! is different than the real position of the arm? Should be it the same?

**Comment by rastaxe** [comment]
Ok, a little update. I used the MoveIt! assistant. If I use the youbot kinematics plugin it does not work. If I use the kdl it works! What did you use?

**Comment by svenschneider** [comment]
I'm using the analytical inverse kinematics solver from this package. Could you please provide more information? Especially, the commands which you have executed and all output you get on the terminal.

Additionally, can you try if the MoveIt! youBot demo is working for you? To do so, execute the following command (with no other ROS nodes running):

```
roslaunch youbot_moveit demo.launch
```

Then try to move around the end-effector with the interactive markers and let me know if it is working.

**Comment by rastaxe** [comment]
I did some other tests and I undestood that the plan fails when it runs on the youbot computer (maybe some timeout is too short?).
By the way:
1) roslaunch youbot_moveit demo.launch works on my computer (I did not tested on the youbot PC since it has no monitor attached)
2) if I run all the programs on the youbot: 
          - roslaunch youbot_driver_ros_interface youbot.launch
          - roslaunch youbot_driver_ros_interface youbot_joint_state_publisher.launch
          - roslaunch youbot_moveit move_group.launch 
      The plan fails with rviz and also with the commander.py. The following is the output with a "go candle" command:  
[ INFO] [1409568957.789114081]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ WARN] [1409568957.790293002]: Execution of motions should always start at the robot's current state. Ignoring the state supplied as start state in the motion planning request
[ INFO] [1409568957.790873872]: Planning attempt 1 of at most 1
[ INFO] [1409568957.792028769]: Starting state is just outside bounds (joint 'arm_joint_1'). Assuming within bounds.
[ INFO] [1409568957.843788767]: No planner specified. Using default.
[ INFO] [1409568957.845305791]: LBKPIECE1: Attempting to use default projection.
[ INFO] [1409568957.862689080]: LBKPIECE1: Starting with 1 states
[ INFO] [1409568963.093217626]: LBKPIECE1: Created 154 (19 start + 135 goal) states in 138 cells (19 start (19 on boundary) + 119 goal (119 on boundary))
[ INFO] [1409568963.093575982]: No solution found after 5.246740 seconds
[ INFO] [1409568963.094266853]: Unable to solve the planning problem

3) if I run:
          - (on YOUBOT) roslaunch youbot_driver_ros_interface youbot.launch
          - (on YOUBOT) roslaunch youbot_driver_ros_interface youbot_joint_state_publisher.launch
          - (other PC) roslaunch youbot_moveit move_group.launch 

   The plan works, except for the fact that I receive some warnings like "arm_joint_4 exceeded I2t
" or "arm_joint_1 over current" and after that the relative joint seems to not work properly.

Do you know if it is possible to run everything on the youbot PC? And if it is possible to avoid these warnings?

Thank you so much!

**Comment by svenschneider** [comment]
The default internal PC of the youBot is indeed very slow, so that this is very likely the problem (as shown by your tests). If you want to use the internal PC, maybe try out different motion planners. They may have better runtime performance, though I cannot really give any hints there.

The I2t and over current issues are due to the joint-level controllers or their configuration. You could try updating the firmware and/or reducing the maximum velocity of the joints. I think, with firmware version 1.4 the issues were solved, while the current firmware version is 2.0. However, for details you should ask KUKA or in the youBot store.

**Comment by svenschneider** [comment]
Closing as issue seems to be resolved.
