### ISSUE TITLE
Does it work with ROS-indigo?

### ISSUE THREAD

**Issue by Ahmed-Nouman** [svenschneider/youbot-manipulation#8]
I am having trouble using it with Ros-Indigo. Does it work for any of you people?

**Comment by svenschneider** [comment]
Currently, I don't have an Indigo setup around, but when I tried it out the last time, everything was working. Unfortunately, your description of the problem is insufficient to help.

**Comment by frederikhegger** [comment]
Dear @Ahmed-Sabanci,
we are working with our youBot under Indigo and this repository. Everything works fine for us.
